language: python
dist: xenial
python:
  - "3.7"
script:
  - pylint --rcfile=etc/pylintrc officium
  - pip install -U sphinx sphinx_rtd_theme && make -C doc html
  - scripts/bringup/bringup-demo.sh
deploy:
  provider: pages
  local-dir: doc/_build/html
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
    python: "3.7"
